name: 'CI'

on:
  pull_request:

jobs:
  lint:
    name: Static Analysis
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v1
      - id: fmt
        run: terraform fmt
      - if: ${{ steps.fmt.outputs.stdout != '' }}
        run: exit 1
